wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/use-cases/eurac/train.py
    python_version: 3.10.13
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709224917.503021
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      - 105
      2:
      - 1
      - 5
      - 53
      - 55
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
num_epochs:
  desc: null
  value: 14
temporal_sampling_size:
  desc: null
  value: 200
seq_length:
  desc: null
  value: 365
ts_range:
  desc: null
  value: 1827
optimizer:
  desc: null
  value: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: False\n    lr: 0.01\n    maximize: False\n    weight_decay:\
    \ 0\n)"
loss_func:
  desc: null
  value: MSELoss()
metric_func:
  desc: null
  value: trainer.mse_metric
train_dl:
  desc: null
  value: <torch.utils.data.dataloader.DataLoader object at 0x14f07344a140>
val_dl:
  desc: null
  value: <torch.utils.data.dataloader.DataLoader object at 0x14f07344aec0>
lr_scheduler:
  desc: null
  value: <torch.optim.lr_scheduler.ReduceLROnPlateau object at 0x14f07344bdc0>
path2weights:
  desc: null
  value: ./checkpoints/weights.pt
device:
  desc: null
  value: cpu
target_names:
  desc: null
  value:
  - vwc
