loader:
  class_path: dataloader.Zebra2HorseDataLoader
  init_args:
    buffer_size: 256

trainer:
  class_path: trainer.Zebra2HorseTrainer
  init_args:
    epochs: 10
    batch_size: 1
    model:
      class_path: cyclegan.CycleGAN
      init_args:
        generator_G:
          class_path: cyclegan.Generator
        generator_F:
          class_path: cyclegan.Generator
        discriminator_X:
          class_path: cyclegan.Discriminator
        discriminator_Y:
          class_path: cyclegan.Discriminator
    compile_conf:
      gen_G_optimizer: {
        class_name: "Adam",
        config: {
            learning_rate: 0.001
        }
      }
      gen_F_optimizer: {
        class_name: "Adam",
        config: {
            learning_rate: 0.001
        }
      }
      disc_X_optimizer: {
        class_name: "Adam",
        config: {
            learning_rate: 0.001
        }
      }
      disc_Y_optimizer: {
        class_name: "Adam",
        config: {
            learning_rate: 0.001
        }
      }
    loggers: []
