pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      download-step:
        class_path: dataloader.TensorflowDataGetter
        init_args:
          data_url: https://drive.google.com/drive/folders/1TnmujO4T-8_j4bCxqNe5HEw9njJIIBQD #https://drive.google.com/drive/folders/15DEq33MmtRvIpe2bNCg44lnfvEiHcPaf
          patch_type: NEAREST
          shuffle: False
          split_ratio: [0.75, 0.25]
          batch_size: 16
          augment: True
          epochs: 1
          target_scale: False
          label_no_cyclone: NONE
          aug_type: ONLY_TCS
          experiment: {
            'DRV_VARS_1': ['fg10', 'msl', 't_500', 't_300'],
            'COO_VARS_1': ['patch_cyclone'],
            'MSK_VAR_1': None
          }

      training-step:
        class_path: trainer.TensorflowTrainer
        init_args:
          epochs: ${pipeline.init_args.steps.download-step.init_args.epochs}
          batch_size: ${pipeline.init_args.steps.download-step.init_args.batch_size}
          network: VGG_V1
          activation: LINEAR
          regularization_strength: NONE
          learning_rate: 0.0001
          loss: MAE
