executor:
  class_path: executor.CycloneExecutor
  init_args:
    run_name: 'default'
    steps:
      - class_path: dataloader.TensorflowDataGetter
        init_args:
          patch_type: NEAREST
          shuffle: False
          split_ratio: [0.75, 0.25]
          batch_size: 16
          augment: True
          epochs: 1
          target_scale: False
          label_no_cyclone: NONE
          aug_type: ONLY_TCS
          experiment: {
            'DRV_VARS_1': ['fg10', 'msl', 't_500', 't_300'],
            'COO_VARS_1': ['patch_cyclone'],
            'MSK_VAR_1': None
          }
      - class_path: trainer.TensorflowTrainer
        init_args:
          network: VGG_V1
          activation: LINEAR
          regularization_strength: NONE
          learning_rate: 0.0001
          loss: MAE
