# General configuration
epochs: 100
strategy: 'ddp'
knots_len: 10
shape: [1]
kappa: 0
m_sq: -1.2
lambd: 0.5
symmetric: True

pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      training-step:
        class_path: normflow.Fitter
        init_args:
          model:
            class_path: normflow.Model
            init_args:
              net_:
                class_path: normflow.nn.DistConvertor_
                init_args:
                  knots_len: ${knots_len}
                  symmetric: ${symmetric}
              prior:
                class_path: normflow.prior.NormalPrior
                init_args:
                  shape: ${shape}
              action:
                class_path: normflow.action.ScalarPhi4Action
                init_args:
                  kappa: ${kappa}
                  m_sq: ${m_sq}
                  lambd: ${lambd}
          config: null
          epochs: ${epochs}
          strategy: ${strategy}
          logger:
            class_path: itwinai.loggers.MLFlowLogger
            init_args:
              experiment_name: "Lattice QCD"
              log_freq: "batch"
