# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# --------------------------------------------------------------------------------------

# Data and logging
data_dir: /p/scratch/intertwin/datasets/imagenet/ILSVRC2012/train/ # tmp_data/
epoch_time_directory: scalability-metrics/epoch-time

# Subset size can be an int or None. Cannot be larger than the length of the dataset. 
# If you wish to set it to "None", you must use "null" as that is what yaml expects
subset_size: 5000 
log_int: 10

# verbose: True
nworker: 4 # num workers dataloader
prefetch: 2

# Model
batch_size: 64 # micro batch size
epochs: 10
lr: 0.001
momentum: 0.5
shuff: False

# Reproducibility
rnd_seed: 10
