lock: export-env
	@echo "NOTE: Run 'make lock' from *whitin* the virtual environment you want to lock!"
	rm -f locks/*
	conda-lock -p linux-64 -p linux-aarch64 -f environment.yml -k explicit --filename-template 'locks/conda-{platform}.lock'

export-env:
	@echo "# DO NOT EDIT: this file is automatically generated via 'make export-env' command" > environment.yml
	mamba env export --from-history -p ./.venv  | grep -v "^prefix: " | grep -v "^name: " >> environment.yml

%: docker/Dockerfile.%
	docker buildx build -t itwin-ai-$@ --load -f $< .

simple: docker/Dockerfile
	docker buildx build -t itwin-ai --load -f $< .
