#!/bin/bash

# general configuration of the job
#SBATCH --job-name=PrototypeTest
#SBATCH --account=intertwin
#SBATCH -o logs_slurm/job-2.out
#SBATCH -e logs_slurm/job-2.err
#SBATCH --time=00:30:00

# configure node and process count on the CM
#SBATCH --partition=develbooster
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=4
#SBATCH --gpus-per-node=4

#SBATCH --exclusive

# gres options have to be disabled for deepv
#SBATCH --gres=gpu:4

# load modules
ml --force purge
ml Stages/2024 GCC OpenMPI CUDA/12 cuDNN 
ml Python CMake HDF5 PnetCDF libaio

# activate environment
source ../../../envAI_juwels/bin/activate

# ON LOGIN NODE download datasets:
# ../../../.venv-pytorch/bin/itwinai exec-pipeline +pipe_key=training_pipeline +pipe_steps=[dataloading_step]

srun itwinai exec-pipeline +pipe_steps=[1]