# General configuration
dataset_root: '/p/scratch/intertwin/datasets/cerfacs/'
epochs: 3
batch_size: 10
lr: 0.001
scenario: '245'
strategy: 'ddp'

# Workflows
pipeline:
   class_path: itwinai.pipeline.Pipeline
   init_args:
     steps:
         preprocessing-step:
           class_path: preprocessing.preprocess_functions_2d_ssp.PreprocessData
           init_args:
               dataset_root: ${dataset_root}
               scenario: ${scenario}
         preprocessing-split-step:
           class_path: preprocessing.preprocess_2d_seasons.SplitPreprocessedData
           init_args:
               scenario: ${scenario} 
         training-step:
             #class_path: src.trainer_dist.XTClimTrainer
           class_path: src.trainer.TorchTrainer
           init_args:
               epochs: ${epochs}
               batch_size: ${batch_size}
               lr: ${lr}
               #strategy: ${strategy}
        
