# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# --------------------------------------------------------------------------------------

# General config
dataset_root: .tmp/
num_classes: 10
batch_size: 64
num_workers_dataloader: 4
pin_memory: False
lr: 0.001
momentum: 0.9
fp16_allreduce: False
use_adasum: False
gradient_predivide_factor: 1.0
epochs: 2
strategy: ddp
test_data_path: mnist-sample-data
inference_model_mlflow_uri: mnist-pre-trained.pth
predictions_dir: mnist-predictions
predictions_file: predictions.csv
class_labels: null
checkpoints_location: checkpoints
checkpoint_every: 1

# Workflows configuration
training_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:
    dataloading_step:
      _target_: dataloader.MNISTDataModuleTorch
      save_path: ${dataset_root}
    training_step:
      _target_: itwinai.torch.trainer.TorchTrainer
      config:
        batch_size: ${batch_size}
        num_workers_dataloader: ${num_workers_dataloader}
        pin_gpu_memory: ${pin_memory}
        optimizer: sgd
        optim_lr: ${lr}
        optim_momentum: ${momentum}
        fp16_allreduce: ${fp16_allreduce}
        use_adasum: ${use_adasum}
        gradient_predivide_factor: ${gradient_predivide_factor}
      model:
        _target_: model.Net
      epochs: ${epochs}
      metrics:
        accuracy:
          _target_: torchmetrics.classification.MulticlassAccuracy
          num_classes: ${num_classes}
        precision:
          _target_: torchmetrics.classification.MulticlassPrecision
          num_classes: ${num_classes}
        recall:
          _target_: torchmetrics.classification.MulticlassRecall
          num_classes: ${num_classes}
      logger:
        _target_: itwinai.loggers.LoggersCollection
        loggers:
          - _target_: itwinai.loggers.ConsoleLogger
            log_freq: 10000
          - _target_: itwinai.loggers.MLFlowLogger
            experiment_name: MNIST classifier
            log_freq: batch 
      strategy: ${strategy}
      checkpoint_every: ${checkpoint_every}
      checkpoints_location: ${checkpoints_location}

      
inference_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:
    - _target_: dataloader.MNISTPredictLoader
      test_data_path: ${test_data_path}
    - _target_: itwinai.torch.inference.MulticlassTorchPredictor
      model:
        _target_: itwinai.torch.inference.TorchModelLoader
        model_uri: ${inference_model_mlflow_uri}
      test_dataloader_kwargs:
        batch_size: ${batch_size}
    - _target_: saver.TorchMNISTLabelSaver
      save_dir: ${predictions_dir}
      predictions_file: ${predictions_file}
      class_labels: ${class_labels}
