# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# --------------------------------------------------------------------------------------

# Find more base image candidates under:
# - https://github.com/interTwin-eu/itwinai/pkgs/container/itwinai
# - https://github.com/interTwin-eu/itwinai/pkgs/container/itwinai-dev
FROM ghcr.io/intertwin-eu/itwinai:torch-skinny-latest

# Add torch MNIST use case
COPY use-cases/mnist/torch/* ./
