executor:
  class_path: itwinai.components.Executor
  init_args:
    steps:
      - class_path: dataloader.MNISTDataModuleTorch
        init_args:
          save_path: .tmp/

      - class_path: itwinai.torch.trainer.TorchTrainerMG
        init_args:
          model:
            class_path: model.Net
          loss:
            class_path: torch.nn.NLLLoss
            init_args:
              reduction: mean
          optimizer_class: torch.optim.SGD
          optimizer_kwargs: 
            lr: 0.001
          train_dataloader_kwargs:
            batch_size: 32
            pin_memory: True
            shuffle: True
          validation_dataloader_kwargs:
            batch_size: 32
            pin_memory: True
            shuffle: False
          epochs: 2
          train_metrics:
            accuracy:
              class_path: torchmetrics.classification.MulticlassAccuracy
              init_args:
                num_classes: 10
            precision:
              class_path: torchmetrics.classification.MulticlassPrecision
              init_args:
                num_classes: 10
            recall:
              class_path: torchmetrics.classification.MulticlassRecall
              init_args:
                num_classes: 10
          logger: 
            - class_path: itwinai.loggers.SimpleLogger
            - class_path: itwinai.loggers.MLFlowLogger
              init_args:
                experiment_name: MNIST classifier
                log_freq: batch 
          strategy: ddp
          checkpoint_every: 1
          cluster:
            class_path: itwinai.torch.cluster.LocalCluster
            init_args:
              gpus: '0,1,2'
              backend: nccl
