downloaded_hdf5_location: calochallenge_data/
dataset_type: "dataset_1_pions"
checkpoint_path: checkpoints/
epochs: 3
strategy: ddp
batch_size: 512
inference_model_mlflow_uri: checkpoints/best_model.pth

dataloading_step:
  class_path: data.CaloChallengeDownloader
  init_args:
    data_path: ${downloaded_hdf5_location}
    dataset_type: ${dataset_type}

training_pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      dataloading_step:
        class_path: data.CalochallengeDataSplitter
        init_args:
          data_path: ${downloaded_hdf5_location}
          dataset_type: ${dataset_type}
          eps: 1.0e-10
          u0up_cut: 3.5 
          u0low_cut: 0.0 
          dep_cut: 600
          width_noise: 5.0e-6 
          fixed_noise: False
          noise: False
          validation_proportion: 0.01
          rnd_seed: 1

      training_step:
        class_path: trainer.CaloChallengeTrainer
        init_args:
          config:
            bayesian: False
            internal_size: 256
            alpha: 1.0e-8
            alpha_logit: 1.0e-6
            log_cond: True
            use_norm: False
            sub_layers: [linear, linear, linear, linear]
            coupling_type: rational_quadratic
            use_extra_dims: True
            n_blocks: 12
            norm: True
            permute_soft: False
            bounds_init: 18
            layers_per_block: 4
            num_bins: 10
            dropout: 0.0
            layer_norm: nn.BatchNorm1d
            layer_act: nn.SiLU
            prior_prec: 5000
            std_init: -15.0
            batch_size: ${batch_size}
            eps: 1.0e-10

            max_lr: 1.e-5
            optim_lr: 1.e-6
          num_epochs: ${epochs}
          checkpoint_path: ${checkpoint_path}
          checkpoint_every: 5
          validation_every: 1
          strategy: ${strategy}
          logger:
            class_path: itwinai.loggers.LoggersCollection
            init_args:
              loggers:
                - class_path: itwinai.loggers.ConsoleLogger
                  init_args:
                    log_freq: 1
                - class_path: itwinai.loggers.MLFlowLogger
                  init_args:
                    experiment_name: Calorimeter simulation (CaloINN) ddp strategy
                    log_freq: batch 
      inference_step:
        class_path: trainer.CaloChallengePredictor
        init_args:
          model:
            class_path: itwinai.torch.inference.TorchModelLoader
            init_args:
              model_uri: ${inference_model_mlflow_uri}
          test_dataloader_kwargs:
            batch_size: ${batch_size}
          config:
            single_energy: null
            num_samples_to_generate: 10000


          
          