pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      - class_path: dataloader.MNISTDataGetter

      - class_path: dataloader.MNISTDataPreproc
        init_args:
          classes: 10

      - class_path: trainer.MNISTTrainer
        init_args:
          epochs: 10
          batch_size: 17

          loss:
            class_path: tensorflow.keras.losses.CategoricalCrossentropy
            init_args:
              from_logits: False

          optimizer: 
            class_path: tensorflow.keras.optimizers.Adam
            init_args: 
                learning_rate: 0.001

          model:
            class_path: itwinai.tensorflow.models.mnist.MNIST_Model
            init_args:
              input_shape: [ 28, 28, 1 ]
              output_shape: 10

          strategy:
            class_path: tensorflow.python.distribute.mirrored_strategy.MirroredStrategy

          # logger: 
          #   - class_path: itwinai.loggers.ConsoleLogger
          #   - class_path: itwinai.loggers.MLFlowLogger
          #     init_args:
          #       experiment_name: MNIST classifier
          #       log_freq: batch 
