# Workflow definition in classical style

# Load with OmegaConf

# Other configuration files to merge with this file via OmegaConf 
conf-dependencies:
  - ./use-cases/mnist/datasets-registry.yml

steps:
  - preprocessing:
      doc: Download and split MNIST dataset into train and test sets
      command: python ./use-cases/mnist/mnist-preproc.py
      env: 
        file: ./use-cases/mnist/preproc-env.yml
        prefix: ./use-cases/mnist/.venv-preproc
      args:
        output: ${datasets.preproc-images.location}
        stage: train
  - ml-training:
      doc: Train a neural network to classify MNIST images
      command: itwinai train
      env: 
        file: ./ai/pytorch-env-freeze.yml
        prefix: ./ai/.venv-pytorch
        source: ./ai
      args:
        train-dataset: ${datasets.preproc-images.location}
        ml-logs: ${datasets.ml-logs.location}
        config: ./use-cases/mnist/mnist-ai-train.yml

# #Workflow definition in CWL style

# workflowFileCWL: use-cases/mnist/workflow.cwl

# preprocessEnvironment:
#   class: Directory
#   path: .venv-preproc

# preprocessScript:
#   class: File
#   path: mnist-preproc.py

# #Placeholder for input dataset
# # preprocessInput:
# #   class: Directory
# #   path:

# preprocessOutput:
#   class: Directory
#   path: ../../data/mnist/preproc-images-train

# #training step
# trainingConfig:
#   class: File
#   path: mnist-ai.yml

# trainingEnvironment:
#   class: Directory
#   path: ../../ai/.venv-training

# trainingCommand: train