# Workflow definition in classical style

# Load with OmegaConf

# Other configuration files to merge with this file via OmegaConf 
conf-dependencies:
  - meta.yml

steps:
  - preprocessing:
      doc: Download and split MNIST dataset into train and test sets
      command: python ${root}/mnist-preproc.py
      env: 
        file: ${root}/env-files/preproc-env.yml
        prefix: ${root}/.venv-preproc
      args:
        output: ${datasets.preproc-images.location}
        stage: train
  - ml-training:
      doc: Train a neural network to classify MNIST images
      command: itwinai train
      env: 
        file: ${ai-root}/env-files/pytorch-lock.yml
        prefix: ${ai-root}/.venv-pytorch
        source: ${ai-root}
      args:
        train-dataset: ${datasets.preproc-images.location}
        ml-logs: ${datasets.ml-logs.location}
        config: ${root}/mnist-ai-train.yml

# #Workflow definition in CWL style

# workflowFileCWL: use-cases/mnist/workflow.cwl

# preprocessEnvironment:
#   class: Directory
#   path: .venv-preproc

# preprocessScript:
#   class: File
#   path: mnist-preproc.py

# #Placeholder for input dataset
# # preprocessInput:
# #   class: Directory
# #   path:

# preprocessOutput:
#   class: Directory
#   path: ../../data/mnist/preproc-images-train

# #training step
# trainingConfig:
#   class: File
#   path: mnist-ai.yml

# trainingEnvironment:
#   class: Directory
#   path: ../../ai/.venv-training

# trainingCommand: train