# I/O
data_dir: tmp_data #/p/project/intertwin/datasets/ImageNet_uncompressed/train
restart_int: 10
verbose: True

# Model
batch_size: 64
epochs: 2 # TODO: increase to 3
lr: 0.001
momentum: 0.5
shuff: False
num_classes: 2 # TODO: reset

# Debugging
testrun: False
nseed: 10
log_int: 10

# Distributed ML
backend: nccl
nworker: 4 # num workers dataloader
prefetch: 2
no_cuda: False


