# I/O
data_dir: /p/largedata2/raise/ImageNet_uncompressed
restart_int: 10
verbose: True

# Model
batch_size: 64
epochs: 2
lr: 0.001
momentum: 0.5
shuff: False

# Debugging
testrun: False
nseed: 10
log_int: 10

# Distributed ML
backend: nccl
nworker: 4 # num workers dataloader
prefetch: 2
no_cuda: False


