training_pipeline:
            class_path: itwinai.pipeline.Pipeline
            init_args:
                steps:
                - class_path: data.FashionMNISTGetter
                - class_path: data.FashionMNISTSplitter
                    init_args: 
                    train_proportion: 0.9
                    validation_proportion: 0.1
                - class_path: trainer.MyTrainer
                    init_args:
                    strategy: ddp
                    epochs: 10
                    checkpoints_location: checkpoints
                    logger:
                        class_path: itwinai.loggers.LoggersCollection
                        init_args:
                        loggers:
                            - class_path: itwinai.loggers.MLFlowLogger
                            init_args:
                                experiment_name: Simple HPO MNIST Experiment
                                log_freq: batch