# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Oleksandr Krochak - Forschungzentrum Juelich
# --------------------------------------------------------------------------------------

num_payloads: 10
tag: train_v0_

mask_maker_dict: {
    model: UNet,
    model_path: ./models/trained_UNet_test_v0.pt
    }

image_tag: train_v0_*_payload_detected.json
image_directory: syn_payload/

mask_tag: train_v0_*_payload_flux.json
mask_directory: syn_payload/
learning_rate: 0.001

training_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:        
    dataloading_step:
      _target_: data.SynthesizeData
      tag: ${tag}
      num_payloads: ${num_payloads}
      name: syntheticData
    dataset_step:  
      _target_: data.GenericDataset
      image_tag: ${image_tag}
      image_directory: ${image_directory}
      mask_tag: ${mask_tag}
      mask_directory: ${mask_directory}
      mask_maker_engine: ${mask_maker_dict}
      do_rot_phase_avg: 1
      do_resize: 1
      resize_size: [128,128]
      mask_binarize_func: "thresh"
    splitter_step:
      _target_: data.DatasetSplitter
      train_proportion: 0.8
      validation_proportion: 0.1
      test_proportion: 0.1
      rnd_seed: 42
      name: Splitter
    training_step:
      _target_: trainer.PulsarTrainer
      model:
       _target_: src.pulsar_analysis.neural_network_models.FilterCNN
      loss:
        _target_: src.pulsar_analysis.neural_network_models.WeightedBCELoss
        pos_weight: 1
        neg_weight: 1
      num_epochs: 3
      store_trained_model_at: ./models/trained_Filter_test_v0.pt
      name: InmaskToMaskTrainer
      config:
        generator: simple #unet
        optimizer: adam
        batch_size: 10 # Set to one because "chunk_size" implicitly decides this
        optim_lr: ${learning_rate}
        save_best: 1
        shuffle_train: 1