apiVersion: v1
kind: Pod
metadata:
  name: 3dgan-train
  annotations:
    slurm-job.vk.io/flags: "-p gpu --gres=gpu:1 --cpus-per-task=4 --mem=100G --ntasks-per-node=1 --nodes=1 --time=00:55:00"
    job.vk.io/singularity-mounts: "--bind /ceph/hpc/data/st2301-itwin-users/egarciagarcia:/exp_data"
    # job.vk.io/pre-exec: "singularity pull /ceph/hpc/data/st2301-itwin-users/itwinai_v9.5.sif docker://ghcr.io/intertwin-eu/itwinai:0.0.1-3dgan-0.4"
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - -c
    - "\" cd /usr/src/app && itwinai exec-pipeline --print-config \
          --config \\$CERN_CODE_ROOT/config.yaml \ 
          --pipe-key training_pipeline \
          -o dataset_location=\\$CERN_DATA_ROOT \ 
          -o pipeline.init_args.steps.training_step.init_args.exp_root=\\$TMP_DATA_ROOT \ 
          -o logs_dir=\\$TMP_DATA_ROOT/ml_logs \ 
          -o distributed_strategy=\\$STRATEGY \ 
          -o devices=\\$DEVICES \ 
          -o hw_accelerators=\\$ACCELERATOR \ 
          -o checkpoints_path=\\$TMP_DATA_ROOT/checkpoints \
          -o max_samples=\\$MAX_DATA_SAMPLES \ 
          -o batch_size=\\$BATCH_SIZE \ 
          -o max_dataset_size=\\$NUM_WORKERS_DL \""
    command:
    - /bin/sh
    env:
    - name: CERN_DATA_ROOT
      value: "/exp_data"
    - name: CERN_CODE_ROOT
      value: "/usr/src/app"
    - name: TMP_DATA_ROOT
      value: "/exp_data"
    - name: MAX_DATA_SAMPLES
      value: "1000"
    - name: BATCH_SIZE
      value: "512"
    - name: NUM_WORKERS_DL
      value: "4"
    - name: ACCELERATOR
      value: "gpu"
    - name: STRATEGY
      value: "auto"
    - name: DEVICES
      value: "auto"

    # - name: MLFLOW_TRACKING_USERNAME
    #   valueFrom:
    #     secretKeyRef:
    #       name: mlflow-server
    #       key: username
    # - name: MLFLOW_TRACKING_PASSWORD
    #   valueFrom:
    #     secretKeyRef:
    #       name: mlflow-server
    #       key: password

    - name: MLFLOW_TRACKING_USERNAME
      value: "XXX"
    - name: MLFLOW_TRACKING_PASSWORD
      value: "XXX"
    image: /ceph/hpc/data/st2301-itwin-users/itwinai_v9.5.sif
    imagePullPolicy: Always
    name: oscar-container
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeSelector:
    kubernetes.io/hostname: vega-new-vk
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300