apiVersion: v1
kind: Pod
metadata:
  name: 3dgan-inference-cpu
  annotations:
    slurm-job.vk.io/flags: "-p gpu --gres=gpu:1 --ntasks-per-node=1 --nodes=1 --time=00:55:00"
    slurm-job.vk.io/singularity-mounts: "--bind /ceph/hpc/data/st2301-itwin-users/egarciagarcia:/exp_data"
    # slurm-job.vk.io/pre-exec: "singularity pull /ceph/hpc/data/st2301-itwin-users/itwinai_v9.5.sif docker://ghcr.io/intertwin-eu/itwinai:0.0.1-3dgan-0.4"
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    # cd to writable location
    - " cd /tmp && itwinai exec-pipeline --print-config \
          --config $CERN_CODE_ROOT/config.yaml \
          --pipe-key inference_pipeline \
          -o dataset_location=$CERN_DATA_ROOT \
          -o logs_dir=$TMP_DATA_ROOT/ml_logs/mlflow_logs \
          -o distributed_strategy=$STRATEGY \
          -o devices=$DEVICES \
          -o hw_accelerators=$ACCELERATOR \
          -o inference_model_uri=$CERN_CODE_ROOT/3dgan-inference.pth \
          -o checkpoints_path=$TMP_DATA_ROOT/checkpoints \
          -o max_dataset_size=$MAX_DATA_SAMPLES \
          -o batch_size=$BATCH_SIZE \
          -o num_workers_dataloader=$NUM_WORKERS_DL \
          -o inference_results_location=$TMP_DATA_ROOT/3dgan-generated-data \
          -o aggregate_predictions=$AGGREGATE_PREDS "
    command:
    - /bin/sh
    - -c
    env:
    - name: CERN_DATA_ROOT
      value: "/exp_data"
    - name: CERN_CODE_ROOT
      value: "/usr/src/app"
    - name: TMP_DATA_ROOT
      value: "/exp_data"
    - name: MAX_DATA_SAMPLES
      value: "5000"
    - name: BATCH_SIZE
      value: "1024"
    - name: NUM_WORKERS_DL
      value: "4"
    - name: AGGREGATE_PREDS
      value: "true"
    - name: ACCELERATOR
      value: "cpu"
    - name: STRATEGY
      value: "auto"
    - name: DEVICES
      value: "auto"
    image: /ceph/hpc/data/st2301-itwin-users/itwinai_v10.1.sif
    imagePullPolicy: Always
    name: oscar-container
    resources:
      limits:
        cpu: "48"
        memory: 150Gi
      requests:
        cpu: "4"
        memory: 20Gi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  nodeSelector:
    kubernetes.io/hostname: vega-new-vk
  tolerations:
  - key: virtual-node.interlink/no-schedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300