# General configuration
surrogate_input: /p/scratch/intertwin/datasets/eurac/input/adg1km_eobs_original.zarr
surrogate_model_output: /p/scratch/intertwin/datasets/eurac/model
tmp_stats: /p/scratch/intertwin/datasets/eurac/stats

experiment: "drought use case convlstm"
run_name: "test_conv"
epochs: 4
random_seed: 1010

training_pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      - class_path: data.ConvRNNDatasetGetterAndSplitter
        init_args:
          surrogate_input: ${surrogate_input}
          dynamic_names: ["precip", "pet", "temp"]
          static_names: [ 'thetaS', 'RootingDepth', 'Swood','KsatVer', "Sl"]
          target_names: [ "vwc","actevap"]
          mask_names: ["mask_missing", "mask_lake"]
          train_temporal_range: ["2016-01-01", "2018-12-31"] 
          test_temporal_range: ["2019-01-01", "2020-12-31"] 
      - class_path: data.ConvRNNProcessor
        init_args:
          dataset: CubeletsDataset
          downsampling_train: 
            class_path: hython.sampler.CubeletsDownsampler
            init_args:
              temporal_downsample_fraction: 0.8
              spatial_downsample_fraction: 1
          downsampling_test: 
            class_path: hython.sampler.CubeletsDownsampler
            init_args:
              temporal_downsample_fraction: 0.8
              spatial_downsample_fraction: 1
      - class_path: trainer.ConvRNNDistributedTrainer
        init_args:
          config:
            experiment: ${run_name}
            batch_size: 32
            lr: 0.001
            rnn_config:
              temporal_subsampling: True
              temporal_subset: 1
              target_names:  [ "vwc","actevap"]
              distributed: True
          model:
            class_path: hython.models.convLSTM.ConvLSTM
            init_args:
              input_dim: 8
              hidden_dim: 24
              output_dim: 2
              kernel_size: [5, 5]
              num_layers: 1
              batch_first: True
              bias: False
              return_all_layers: False
          strategy: ddp
          epochs: ${epochs}
          random_seed: ${random_seed}
