pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      download-step:
        class_path: dataloader.LSTMDataGetter
        init_args:
          wd: "/Users/iluise/cernbox/interTwin/hython/data/datademo" 
          fp_dynamic_forcings: "/Users/iluise/cernbox/interTwin/hython/data/datademo/forcings.nc" 
          fp_wflow_static_params:  "/Users/iluise/cernbox/interTwin/hython/data/datademo/staticmaps.nc" 
          fp_target: "/Users/iluise/cernbox/interTwin/hython/data/datademo/output.nc" 
          dynamic_names: ["precip", "pet", "temp"] 
          static_names: [ 'M', 'thetaS', 'RootingDepth', 'Kext', 'Sl', 'Swood', 'TT', 'KsatHorFrac'] 
          target_names: [ "vwc"] #, "actevap" ], 
          timeslice: ["2016-01-01","2020-12-31"] 
          intervals: [10, 10]
          train_origin: [0, 0] 
          valid_origin: [5, 5] 
          spatial_batch_size: 256
          # temporal_sampling_size: 200 
          # seq_length: 365 
          # hidden_size: 128 
          # input_size: 3 #number of dynamic predictors - user_input

      training-step:
        class_path: trainer.LSTMTrainer
        init_args:
          epochs: 2
          spatial_batch_size: 256
          temporal_sampling_size: 200 
          seq_length: 365 
          hidden_size: 128 
          input_size: 3 #number of dynamic predic
          path2models: "./checkpoints"
          dynamic_names: ["precip", "pet", "temp"] 
          static_names: [ 'M', 'thetaS', 'RootingDepth', 'Kext', 'Sl', 'Swood', 'TT', 'KsatHorFrac'] 
          target_names: [ "vwc"] #, "actevap" ], 
