# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# - Kalliopi Tsolaki <kalliopi.tsolaki@cern.ch> - CERN
# --------------------------------------------------------------------------------------

# Main configurations
dataset_location: exp_data/
dataset_url: https://drive.google.com/drive/folders/1ooUIfkhpokvwh4-7qPxX084N7-LgqnIL
hw_accelerators: auto
distributed_strategy: ddp_find_unused_parameters_true
devices: auto
checkpoints_path: checkpoints
logs_dir: ml_logs
mlflow_tracking_uri: mlruns
batch_size: 4
train_dataset_proportion: 0.7
num_workers_dataloader: 0
max_epochs: 2
max_dataset_size: 48
random_seed: 4231162351
inference_results_location: 3dgan-generated-data/
inference_model_uri: 3dgan-inference.pth
aggregate_predictions: false
num_nodes: 1
provenance_verbose: true

# Dataloading step is common and can be reused
dataloading_step:
  _target_: dataloader.Lightning3DGANDownloader
  data_path: ${dataset_location}
  data_url: ${dataset_url}

# AI workflows
training_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:
    dataloading_step: ${dataloading_step}

    training_step:
      _target_: trainer.Lightning3DGANTrainer
      # NOTE: before pushing to the repo, disable logging to prevent slowing down unit tests
      # logger:
      #   _target_: itwinai.loggers.LoggersCollection
      #   loggers:
      #     # - _target_: itwinai.loggers.ConsoleLogger
      #     #   log_freq: 100
      #     # - _target_: itwinai.loggers.MLFlowLogger
      #     #   experiment_name: 3DGAN
      #     #   log_freq: batch
      #     - _target_: itwinai.loggers.Prov4MLLogger
      #       provenance_save_dir: mllogs/prov_logs
      #       experiment_name: 3DGAN
      #       log_freq: batch
      #       log_on_workers: -1
      #     # - _target_: itwinai.loggers.WandBLogger
      #     #   log_freq: batch
      config:
        seed_everything: ${random_seed}
        trainer:
          accelerator: ${hw_accelerators}
          accumulate_grad_batches: 1
          barebones: false
          benchmark: null
          # callbacks:
          #   - _target_: lightning.pytorch.callbacks.early_stopping.EarlyStopping
          #     monitor: val_generator_loss
          #     patience: 2
          #   - _target_: lightning.pytorch.callbacks.lr_monitor.LearningRateMonitor
          #     logging_interval: step
          #   - _target_: lightning.pytorch.callbacks.ModelCheckpoint
          #     dirpath: ${checkpoints_path}
          #     filename: best-checkpoint
          #     mode: min
          #     monitor: val_generator_loss
          #     save_top_k: 1
          #     verbose: true
          check_val_every_n_epoch: 1
          default_root_dir: null
          detect_anomaly: false
          deterministic: null
          devices: ${devices}
          num_nodes: ${num_nodes}
          enable_checkpointing: true
          enable_model_summary: null
          enable_progress_bar: null
          fast_dev_run: false
          gradient_clip_algorithm: null
          gradient_clip_val: null
          inference_mode: true
          limit_predict_batches: null
          limit_test_batches: null
          limit_train_batches: null
          limit_val_batches: null
          log_every_n_steps: 1
          # logger:
          #   - _target_: lightning.pytorch.loggers.CSVLogger
          #     name: 3DGAN
          #     save_dir: ${logs_dir}
          #   - _target_: lightning.pytorch.loggers.MLFlowLogger
          #     experiment_name: 3DGAN
          #     save_dir: null
          #     tracking_uri: ${mlflow_tracking_uri}
          #     log_model: all
          max_epochs: ${max_epochs}
          max_time: null
          min_epochs: null
          min_steps: null
          num_sanity_val_steps: null
          overfit_batches: 0.0
          plugins: null
          profiler: null
          reload_dataloaders_every_n_epochs: 0
          strategy: ${distributed_strategy}
          sync_batchnorm: false
          use_distributed_sampler: true
          val_check_interval: null
        model:
          class_path: model.ThreeDGAN
          init_args:
            latent_size: 256
            loss_weights: [3, 0.1, 25, 0.1]
            power: 0.85
            lr: 0.001
            checkpoints_dir: ${checkpoints_path}
            provenance_verbose: ${provenance_verbose}
        data:
          class_path: dataloader.ParticlesDataModule
          init_args:
            datapath: ${dataset_location}
            batch_size: ${batch_size}
            num_workers: ${num_workers_dataloader}
            max_samples: ${max_dataset_size}
            train_proportion: ${train_dataset_proportion}

inference_pipeline:
  _target_: itwinai.pipeline.Pipeline
  steps:
    dataloading_step: ${dataloading_step}

    inference_step:
      _target_: trainer.Lightning3DGANPredictor
      model:
        _target_: trainer.LightningModelLoader
        model_uri: ${inference_model_uri}

      config:
        seed_everything: ${random_seed}
        trainer:
          accelerator: ${hw_accelerators}
          accumulate_grad_batches: 1
          barebones: false
          benchmark: null
          check_val_every_n_epoch: 1
          default_root_dir: null
          detect_anomaly: false
          deterministic: null
          devices: ${devices}
          enable_checkpointing: true
          enable_model_summary: null
          enable_progress_bar: null
          fast_dev_run: false
          gradient_clip_algorithm: null
          gradient_clip_val: null
          inference_mode: true
          limit_predict_batches: null
          limit_test_batches: null
          limit_train_batches: null
          limit_val_batches: null
          log_every_n_steps: 2
          logger:
          #   - _target_: lightning.pytorch.loggers.CSVLogger
          #     save_dir: ml_logs/csv_logs
            _target_: lightning.pytorch.loggers.MLFlowLogger
            experiment_name: 3DGAN
            save_dir: ${logs_dir}
            log_model: all
          max_epochs: ${max_epochs}
          max_steps: 20
          max_time: null
          min_epochs: null
          min_steps: null
          num_sanity_val_steps: null
          overfit_batches: 0.0
          plugins: null
          profiler: null
          reload_dataloaders_every_n_epochs: 0
          strategy: ${distributed_strategy}
          sync_batchnorm: false
          use_distributed_sampler: true
          val_check_interval: null

        model:
          class_path: model.ThreeDGAN
          init_args:
            latent_size: 256
            loss_weights: [3, 0.1, 25, 0.1]
            power: 0.85
            lr: 0.001
            checkpoints_dir: ${checkpoints_path}
        data:
          class_path: dataloader.ParticlesDataModule
          init_args:
            datapath: ${dataset_location}
            batch_size: ${batch_size}
            num_workers: ${num_workers_dataloader}
            max_samples: ${max_dataset_size}

    saver_step:
      _target_: saver.ParticleImagesSaver
      save_dir: ${inference_results_location}
      aggregate_predictions: ${aggregate_predictions}
