apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: torchrun-cpu
spec:
  nprocPerNode: "2"
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cern.ch/itwinai/dist-ml/itwinai-slim:0.0.7
              command:
                - "torchrun"
                - "/app/main.py"
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: pytorch
              image: registry.cern.ch/itwinai/dist-ml/itwinai-slim:0.0.7
              command:
                - "torchrun"
                - "/app/main.py"
