# Configuration using entire synthetic dataset that is generated prior to running the pipeline
root_folder: /p/scratch/intertwin/datasets/virgo
data_root: ./data
epochs: 2
batch_size: 2
learning_rate: 0.0001
strategy: ddp
checkpoint_path: checkpoints/epoch_{}.pth

training_pipeline:
  class_path: itwinai.pipeline.Pipeline
  init_args:
    steps:
      - class_path: data.TimeSeriesDatasetSplitter
        init_args:
          train_proportion: 0.9
          validation_proportion: 0.1
          rnd_seed: 42
          root_folder: ${root_folder}
      - class_path: trainer.NoiseGeneratorTrainer
        init_args:
          generator: simple #unet
          batch_size: ${batch_size}
          num_epochs: ${epochs}
          strategy: ${strategy}
          checkpoint_path: ${checkpoint_path}
          random_seed: 17
          validation_every: 0
          learning_rate: ${learning_rate}
          logger:
            class_path: itwinai.loggers.LoggersCollection
            init_args:
              loggers:
                - class_path: itwinai.loggers.ConsoleLogger
                  init_args:
                    log_freq: 1
                - class_path: itwinai.loggers.MLFlowLogger
                  init_args:
                    experiment_name: Noise simulator (Virgo)
                    log_freq: batch 
          
