# If you use this with in the runall or scaling mode, keep in mind that the strategies
# will change, as well as the number of nodes. 

mode: single # "single", "runall" or "scaling-test" - defaults to "single"
dist_strat: deepspeed # "ddp", "deepspeed" or "horovod"

account: intertwin
time: 00:11:11
partition: develbooster

# Keep in mind that these will be overwritten if "mode" is not "single", and that
# if you override the dist_strat in the CLI, then these will already have evaluated
# and thus might not correspond. Thus, we suggest you only change the dist_strat in
# the config and avoid overriding it in the CLI.
std_out: slurm_jobs/${dist_strat}.out
err_out: slurm_jobs/${dist_strat}.err
job_name: virgo-${dist_strat}-job

num_nodes: 1
num_tasks_per_node: 1
gpus_per_node: 4
cpus_per_gpu: 4

python_venv: .venv
pipe_key: training_pipeline
