PATH2FILES = './data/datasets/'
PATH4CHECKPOINTS = './data/checkpoints/'
PATH4IMAGES = './data/images/'
FILENAME = 'test_dataset.npy' #'joint_dataset_8_classes_real_remix_128x128.npy'
LABELS = 'test_dataset_labels.npy' #'joint_dataset_8_classes_real_remix_labels.npy'