# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# --------------------------------------------------------------------------------------

name: "Build and Test Container"
description: "Builds, tests, and optimizes disk space for a container image"
inputs:
  free-disk-space:
    description: "Whether to free disk space before running the workflows"
    required: false
    default: "true"
  base-img-name:
    description: "Base image name"
    required: true
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  nickname:
    description: "Name of the container flavour, such as 'torch', 'torch-slim', and 'jhub-slim'"
    required: true
  tag-template:
    description: "Tag template for the image"
    required: true
  release:
    description: "true if triggered during a release, false otherwise"
    required: false
    default: "true"
  skip-hpc:
    description: "Skip HPC-related tests (in release pipeline)"
    required: false
    default: "false"
  skip-singularity:
    description: "Avoid publishing Singularity image"
    required: false
    default: "false"
  docker-token:
    description: "Docker secret auth token"
    required: true
  interlink-values:
    description: "Interlink virtual kubelet (VK) configuration file (secret)"
    required: true
  dagger-cloud-token:
    description: "Dagger cloud secret token"
    required: true
  commit-hash:
    description: "commit hash"
    required: false
    default: "unk-commit-hash"
  singularity-password:
    description: "Password for Singularity registry"
    required: false
    default: null
  singularity-username:
    description: "Username for Singularity registry"
    required: false
    default: null

runs:
  using: "composite"
  steps:

    - name: Maximize Disk Space
      if: inputs.free-disk-space == 'true'
      uses: easimon/maximize-build-space@v10
      with:
        # Reserve space on root for docker/dagger cache
        build-mount-path: /docker
        root-reserve-mb: 2048
        overprovision-lvm: false
        swap-size-mb: 4096
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Move Docker directory
      if: inputs.free-disk-space == 'true'
      shell: bash
      run: |
        sudo mv /var/lib/docker /docker/ &&
        sudo ln -s /docker/docker /var/lib/docker &&
        sudo systemctl restart docker

    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   with:
    #     detached: true

    - name: Check Inputs
      shell: bash
      run: |
        echo &&
        echo skip hpc flag: $([[ "${{ inputs.skip-hpc }}" == "true" ]] && echo '--skip-hpc' || echo '')

    - name: Delete unnecessary tools and packages
      if: inputs.free-disk-space == 'true'
      shell: bash
      run: |
        rm -rf /opt/hostedtoolcache &&
        curl -fsSL https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh | bash
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3

    - name: Get Repo Owner
      id: get_repo_owner
      shell: bash
      run: echo "name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

    # Login to Docker container registry
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.docker-token }}

    # Login to Singularity container registry
    - name: Login to Harbor Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cern.ch
        username: ${{ inputs.singularity-username }}
        password: ${{ inputs.singularity-password }}

    - name: Prepare Environment Variables
      shell: bash
      run: |
        echo "COMMIT_HASH=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
        BASE_IMG_DIGEST=$(echo "${{ inputs.base-img-name }}" | cut -d ':' -f 1)@$(docker buildx imagetools inspect ${{ inputs.base-img-name }} | grep "Digest:" | head -n 1 | awk '{print $2}')
        echo "BASE_IMG_DIGEST=$BASE_IMG_DIGEST" >> "$GITHUB_ENV"
        docker system prune -af

    # This pipeline runs when NOT creating a new release
    - name: Run Integration Test (development pipeline)
      if: inputs.release == 'false'
      uses: dagger/dagger-for-github@v7
      with:
        workdir: ci
        verb: call
        args: >-
          --nickname ${{ inputs.nickname }}
          --docker-registry ghcr.io/intertwin-eu
          --singularity-registry registry.cern.ch/itwinai
          --image itwinai-dev
          build-container
          --context ..
          --dockerfile ${{ inputs.dockerfile }}
          --build-args "COMMIT_HASH=${{ env.COMMIT_HASH }},BASE_IMG_NAME=${{ inputs.base-img-name }},BASE_IMG_DIGEST=${{ env.BASE_IMG_DIGEST }}"
          dev-pipeline
          --tag-template ${{ inputs.tag-template }}
          --framework TORCH
          --password env:SINGULARITY_PWD
          --username env:SINGULARITY_USR
          $([[ "${{ inputs.skip-singularity }}" == "true" ]] && echo '--skip-singularity' || echo '')
        cloud-token: ${{ inputs.dagger-cloud-token }}
        version: "latest"
      env:
          INTERLINK_VALUES: ${{ inputs.interlink-values }}
          SINGULARITY_PWD: ${{ inputs.singularity-password }}
          SINGULARITY_USR: ${{ inputs.singularity-username }}
    
    # This pipeline runs exclusively upon release
    - name: Run Integration Test (release pipeline)
      if: inputs.release == 'true'
      uses: dagger/dagger-for-github@v7
      with:
        workdir: ci
        verb: call
        args: >-
          --tag "${{ env.COMMIT_HASH }}-${{ inputs.nickname }}"
          --nickname ${{ inputs.nickname }}
          --image itwinai
          --docker-registry ghcr.io/intertwin-eu
          --singularity-registry registry.cern.ch/itwinai
          build-container
          --context ..
          --dockerfile ${{ inputs.dockerfile }}
          --build-args "COMMIT_HASH=${{ env.COMMIT_HASH }},BASE_IMG_NAME=${{ inputs.base-img-name }},BASE_IMG_DIGEST=${{ env.BASE_IMG_DIGEST }}"
          release-pipeline
          --values env:INTERLINK_VALUES
          --framework TORCH
          --tag-template ${{ inputs.tag-template }}
          --password env:SINGULARITY_PWD
          --username env:SINGULARITY_USR
          $([[ "${{ inputs.skip-hpc }}" == "true" ]] && echo '--skip-hpc' || echo '')
          $([[ "${{ inputs.skip-singularity }}" == "true" ]] && echo '--skip-singularity' || echo '')
        cloud-token: ${{ inputs.dagger-cloud-token }}
        version: "latest"
      env:
          INTERLINK_VALUES: ${{ inputs.interlink-values }}
          SINGULARITY_PWD: ${{ inputs.singularity-password }}
          SINGULARITY_USR: ${{ inputs.singularity-username }}
