name: integration-tests 

on:
  push:
    #branches: [main,next,next2next]
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        # run: |
        #     rm -rf /opt/hostedtoolcache &&
        #     curl -fsSL https://raw.githubusercontent.com/apache/flink/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh | bash
      - name: Integration Test
        uses: dagger/dagger-for-github@v6
        with:
          workdir: ci
          verb: call
          args: build-container --context=.. --dockerfile=../env-files/torch/Dockerfile publish
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: "latest"