# --------------------------------------------------------------------------------------
# Part of the interTwin Project: https://www.intertwin.eu/
#
# Created by: Matteo Bunino
#
# Credit:
# - Matteo Bunino <matteo.bunino@cern.ch> - CERN
# --------------------------------------------------------------------------------------

name: Container CI 2

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - base-img-name: "nvcr.io/nvidia/pytorch:24.05-py3"
            dockerfile: "../env-files/Dockerfile" # "../env-files/torch/Dockerfile"
            flavour-name: "torch"
            tag-template: '${itwinai_version}-torch${framework_version}-${os_version}'
            skip-hpc: true
          - base-img-name: "python:3.10-slim"
            dockerfile: "../env-files/Dockerfile" # "../env-files/torch/slim.Dockerfile"
            flavour-name: "torch-slim"
            tag-template: '${itwinai_version}-slim-torch${framework_version}-${os_version}'
            skip-hpc: true
          - base-img-name: "jupyter/scipy-notebook:python-3.10.11"
            dockerfile: "../env-files/Dockerfile" # "../env-files/torch/jupyter/slim.Dockerfile"
            flavour-name: "jhub-slim"
            tag-template: 'jhub-slim-${itwinai_version}-torch${framework_version}-${os_version}'
            skip-hpc: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Test with Custom Action
        uses: ./.github/actions/build-container
        with:
          base-img-name: ${{ matrix.config.base-img-name }}
          dockerfile: ${{ matrix.config.dockerfile }}
          flavour-name: ${{ matrix.config.flavour-name }}
          tag-template: ${{ matrix.config.tag-template }}
          skip-hpc: ${{ matrix.config.skip-hpc }}