name: Test workflows based on torch
on: null

# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

jobs:
  torch_tests:
    name: Run pytest for torch
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest
      volumes:
        - ${{ github.workspace }}/src:/repo/src
        - ${{ github.workspace }}/use-cases:/repo/use-cases
        - ${{ github.workspace }}/tests:/repo/tests
        - ${{ github.workspace }}/env-files:/repo/env-files
        - ${{ github.workspace }}/pyproject.toml:/repo/pyproject.toml
        - ${{ github.workspace }}/Makefile:/repo/Makefile
    steps:
    - name: Install environment
      run: |
        ls -la $(pwd) && 
        ls -la /repo && 
        cd /repo &&
        pip install --no-cache /repo[dev]
    
    - name: Run tests
      run: |
        which pip &&
        which pip3 &&
        which python &&
        which python3

    - name: Run tests
      run: pytest -v tests/
      # run: |
      #   whoami &&
      #   pwd &&
      #   ls -la $(pwd) &&
      #   ls -la /repo
      # #   # Now the repository code is available inside the Docker container
      # #   # You can use it as needed
      # #   cd ${{ github.workspace }} &&
      # #   # Run your commands here
      # #   ls -la . &&
      # #   ls -la ${{ github.workspace }} && 
      # #   ls -la ${{ github.workspace }}/.. && 
      # #   pwd &&
      # #   echo  ${{ github.workspace }} &&
      # #   pip install .
