name: Test workflows based on torch
on: [push]

jobs:

  my_job1:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Check workspace
        shell: bash -l {0}
        run: ls -la ${{ github.workspace }}

  my_job:
    runs-on: ubuntu-latest
    container:
      image: python:3.9 #pytorch/pytorch:latest # docker://{docker-image-name}:{tag}
      volumes: 
        - ${{ github.workspace }}:/repo
    steps:
    # - name: Cache Docker image layers
    #   uses: actions/cache@v2
    #   with:
    #     path: /var/lib/docker/image
    #     key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
    - name: Run commands in container
      # run: ls -la /repo
      run: |
        whoami &&
        pwd &&
        ls -la $(pwd)
      #   # Now the repository code is available inside the Docker container
      #   # You can use it as needed
      #   cd ${{ github.workspace }} &&
      #   # Run your commands here
      #   ls -la . &&
      #   ls -la ${{ github.workspace }} && 
      #   ls -la ${{ github.workspace }}/.. && 
      #   pwd &&
      #   echo  ${{ github.workspace }} &&
      #   pip install .
